### ISSUE TITLE
It's not working? on pmmp & mcbe 1.16.201

### ISSUE THREAD

**Issue by lixworth** [yesdog/Waterdog#169]
It's always "Disconnected from Server ",after click ok, it displays "Connect to external server..",finally time out .
The config is woking on nukkit servers ,but it not use the latest version.
And the console has not any output when I try to connect server. 

The config :
```
max_mtu: -1
connection_throttle: 4000
replace_username_spaces: true
use_xuid_for_uuid: true
online_mode: true
remote_ping_timeout: 5000
groups:
  LixWorth:
  - admin
servers:
  lobby:
    raknet: true
    motd: Lobby
    transfer_group: lobby
    address: localhost:19133
    restricted: false

remote_ping_cache: -1
connection_throttle_limit: 3
listeners:
- query_port: 19132
  motd: §lBAQC || CHINA
  tab_list: GLOBAL_PING
  query_enabled: true
  proxy_protocol: false
  ping_passthrough: false
  raknet: true
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:19132
  max_players: 50
  tab_size: 60
  force_default_server: true
  forced_hosts:
    127.0.0.1: lobby
server_connect_timeout: 5000
player_limit: -1
bedrock_encryption: true
ip_forward: false
disabled_commands:
- version
- help
log_pings: true
forge_support: true
log_commands: true
stats: 447fc071-9136-4385-8562-91a70fc800c8
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.demo
  admin:
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
prevent_proxy_connections: false
timeout: 30000

```
