### ISSUE TITLE
Report an error！

### ISSUE THREAD

**Issue by Cain5859** [yesdog/Waterdog#37]
[15:13:14] [Netty Worker IO Thread #1/ERROR]: [/]DownstreamBridge <-> [lobby] - encountered exception
io.netty.handler.codec.DecoderException: Error decoding packet class PluginMessage with contents:
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 75 12 6d 69 6e 65 63 72 61 66 74 3a 72 65 67 69 |u.minecraft:regi|
|00000010| 73 74 65 72 70 73 3a 69 72 00                   |sterps:ir.      |
+--------+-------------------------------------------------+----------------+
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:94) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:13) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(21) + length(112) exceeds writerIndex(26): PooledSlicedByteBuf(ridx: 21, widx: 26, cap: 26/26, unwrapped: PooledUnsafeDirectByteBuf(ridx: 27, widx: 65483, cap: 65536))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1428) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1411) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.netty.buffer.AbstractByteBuf.readSlice(AbstractByteBuf.java:872) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at net.md_5.bungee.protocol.packet.PluginMessage.read(PluginMessage.java:97) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at io.github.waterfallmc.travertine.protocol.MultiVersionPacketV17.read0(MultiVersionPacketV17.java:27) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:72) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7fda22d:227]
	... 25 more
[15:13:14] [Netty Worker IO Thread #1/INFO]: [Cain5859] disconnected with: The server you were previously on went down, you have been connected to a fallback server

**Comment by Seth2482** [comment]
I met the same problem when I had connected a JE server and tried to transfer to a BE server.
BE Server: Altay & BDS
JE Server: Spigot 1.13.2 (installed [ProtocolSupport](https://github.com/yesdog/ProtocolSupport) )
Client: Minecraft Win10 1.11.4

**Comment by Xernium** [comment]
@Cain5859 @Seth2482 Whats your Waterdog config? Please post a gist with a reference here and or highlight the servers in question (also please cut IP addresses from the config as that info shouldn't be leaked)

**Comment by Seth2482** [comment]
I'm sorry that I made a mistake in describing my problem,
Actually, I had been in a BE server and tried to transfer to a JE server.
However,I can't transfer to a BE server from JE server either.

Here is my Waterdog config
```yml
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  raknet: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 1
  tab_size: 60
  force_default_server: true
- query_port: 19134
  motd: 梦幻冬城我的世界
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  raknet: true
  priorities:
  - lobby2
  bind_local_address: true
  host: 0.0.0.0:19134
  max_players: 20
  tab_size: 60
  force_default_server: true
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
log_commands: false
player_limit: -1
ip_forward: true
groups:
  md_5:
  - admin
use_xuid_for_uuid: true
connection_throttle: 4000
replace_username_spaces: true
stats: 03432595-4370-4e86-bb2a-49d70e64ee57
online_mode: false
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    raknet: false
    motd: 大厅服
    transfer_group: default
    address: 127.0.0.1:25565
    restricted: false
  realworld:
    raknet: true
    motd: 生存服
    transfer_group: default
    address: 127.0.0.1:19133
    restricted: false
  lobby2:
    raknet: true
    motd: 生存服大厅
    transfer_group: default
    address: 127.0.0.1:19132
    restricted: false
```

When I tried to transfer from lobby2(altay server) to lobby(Spogit server),I disconnected from the server,and the above error message appeared in the console.
